modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/dodogang/crumbs/issues"
license = "MIT; Assets licensed as All Rights Reserved"

[[mods]]
modId = "crumbs"
version = "${version}"
displayName = "Crumbs"
authors = "Dodo Gang"
description = '''
Building mod which adds various blocks tuned to fit with vanilla minecraft.
'''
#logoFile = ""

[[dependencies.crumbs]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.crumbs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
