# This workflow will build a package using Gradle

name: Check Builds For Errors

on: [ pull_request, push ]

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        # Use these Java versions
        java: [ 17 ]
        # and run on both Linux and Windows
        os: [ ubuntu-20.04, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build Fabric
        run: ./gradlew :Fabric:build
      - name: Capture Fabric build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Fabric/build/libs/

      - name: Build Forge
        run: ./gradlew :Forge:build
      - name: Capture Forge build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Forge/build/libs/

      - name: Build Quilt
        run: ./gradlew :Quilt:build
      - name: Capture Quilt build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Forge/build/libs/
